name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: self-hosted  # Adjust this as per your self-hosted runner configuration

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Install dependencies
        run: npm ci --only=prod  # Use npm ci for faster and consistent installs

      - name: Docker Build and Push
        run: |
          docker build -t swiggy-clone .
          docker tag swiggy-clone isika05/swiggy-clone:latest
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push isika05/swiggy-clone:latest
        env:
          DOCKER_CLI_ACI: 1
